-- NEVER SETTLE sample data: 6 categories and 12 demo products (optional).
-- Import AFTER install.sql. Replace or delete the demo products from the admin panel before launch.
SET NAMES utf8mb4;

INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`, `sort_order`, `created_at`) VALUES (1,'T-shirts','tshirts','Heavyweight and oversized tees for every day.','/images/categories/tshirts.jpg',0,'2026-09-26 13:11:51');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`, `sort_order`, `created_at`) VALUES (2,'Pants','pants','Cargos and chinos that hold their shape.','/images/categories/pants.jpg',1,'2026-09-26 13:11:51');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`, `sort_order`, `created_at`) VALUES (3,'Punjabis','punjabis','Festive and everyday punjabis in cotton and linen.','/images/categories/punjabis.jpg',2,'2026-09-26 13:11:51');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`, `sort_order`, `created_at`) VALUES (4,'Kurtas','kurtas','Short and classic kurtas for easy, polished days.','/images/categories/kurtas.jpg',3,'2026-09-26 13:11:51');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`, `sort_order`, `created_at`) VALUES (5,'Shoes','shoes','Sneakers and leather shoes built for miles.','/images/categories/shoes.jpg',4,'2026-09-26 13:11:51');
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`, `sort_order`, `created_at`) VALUES (6,'Wallets','wallets','Leather wallets and card holders.','/images/categories/wallets.jpg',5,'2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (1,'Core Heavyweight Tee','core-heavyweight-tee','<p>220gsm combed cotton with a relaxed body and a ribbed collar that keeps its shape wash after wash.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',1,99000,NULL,'new',1,1,'2026-09-26 13:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (2,'Signature Oversized Tee','signature-oversized-tee','<p>Boxy, drop-shoulder fit in 240gsm cotton jersey. Made to be worn loose.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',1,119000,NULL,'',1,1,'2026-09-26 12:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (3,'Motion Cargo Pants','motion-cargo-pants','<p>Twill cargo pants with a tapered leg, six pockets and a soft brushed waistband.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',2,245000,NULL,'new',1,1,'2026-09-26 11:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (4,'Everyday Chino Pants','everyday-chino-pants','<p>Stretch cotton chinos with a clean straight cut for office days and weekends.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',2,219000,259000,'',1,1,'2026-09-26 10:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (5,'Eid Cotton Punjabi','eid-cotton-punjabi','<p>Fine cotton punjabi with tonal embroidery along the placket and concealed side pockets.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',3,349000,NULL,'new',1,0,'2026-09-26 09:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (6,'Embroidered Linen Punjabi','embroidered-linen-punjabi','<p>Linen-blend punjabi with gold thread embroidery and a mandarin collar. Breathable for long festive days.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',3,429000,499000,'',1,0,'2026-09-26 08:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (7,'Short Linen Kurta','short-linen-kurta','<p>Hip-length kurta in washed linen with side slits. Pairs with chinos or jeans.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',4,229000,NULL,'',1,0,'2026-09-26 07:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (8,'Classic Cotton Kurta','classic-cotton-kurta','<p>Mid-length cotton kurta with a button placket and a comfortable regular fit.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',4,259000,NULL,'new',1,0,'2026-09-26 06:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (9,'Street Runner Sneakers','street-runner-sneakers','<p>Low-top sneakers with a cushioned EVA midsole and a grippy rubber outsole.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',5,499000,NULL,'',1,0,'2026-09-26 05:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (10,'Leather Penny Loafers','leather-penny-loafers','<p>Full-grain leather loafers with a padded insole and stitched leather sole.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',5,549000,599000,'',1,0,'2026-09-26 04:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (11,'Slim Leather Bifold','slim-leather-bifold','<p>Genuine leather bifold with six card slots, a note pocket and hand-finished edges.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',6,129000,NULL,'',1,0,'2026-09-26 03:11:51','2026-09-26 13:11:51');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `details`, `category_id`, `price`, `compare_at`, `tags`, `is_active`, `is_featured`, `created_at`, `updated_at`) VALUES (12,'Card Holder Wallet','card-holder-wallet','<p>Minimal card holder with four slots and a centre pocket. Fits front pockets easily.</p>','<p>Wash cold, inside out. Dry in the shade.</p>',6,89000,NULL,'new',1,0,'2026-09-26 02:11:51','2026-09-26 13:11:51');
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (1,1,'/images/products/tee1a.jpg','Core Heavyweight Tee',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (2,1,'/images/products/tee1b.jpg','Core Heavyweight Tee',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (3,2,'/images/products/tee2a.jpg','Signature Oversized Tee',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (4,2,'/images/products/tee2b.jpg','Signature Oversized Tee',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (5,3,'/images/products/pant1a.jpg','Motion Cargo Pants',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (6,3,'/images/products/pant1b.jpg','Motion Cargo Pants',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (7,4,'/images/products/pant2a.jpg','Everyday Chino Pants',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (8,4,'/images/products/pant2b.jpg','Everyday Chino Pants',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (9,5,'/images/products/punj1a.jpg','Eid Cotton Punjabi',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (10,5,'/images/products/punj1b.jpg','Eid Cotton Punjabi',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (11,6,'/images/products/punj2a.jpg','Embroidered Linen Punjabi',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (12,6,'/images/products/punj2b.jpg','Embroidered Linen Punjabi',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (13,7,'/images/products/kurt1a.jpg','Short Linen Kurta',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (14,7,'/images/products/kurt1b.jpg','Short Linen Kurta',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (15,8,'/images/products/kurt2a.jpg','Classic Cotton Kurta',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (16,8,'/images/products/kurt2b.jpg','Classic Cotton Kurta',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (17,9,'/images/products/shoe1a.jpg','Street Runner Sneakers',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (18,9,'/images/products/shoe1b.jpg','Street Runner Sneakers',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (19,10,'/images/products/shoe2a.jpg','Leather Penny Loafers',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (20,10,'/images/products/shoe2b.jpg','Leather Penny Loafers',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (21,11,'/images/products/wal1a.jpg','Slim Leather Bifold',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (22,11,'/images/products/wal1b.jpg','Slim Leather Bifold',1);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (23,12,'/images/products/wal2a.jpg','Card Holder Wallet',0);
INSERT INTO `product_images` (`id`, `product_id`, `url`, `alt`, `sort_order`) VALUES (24,12,'/images/products/wal2b.jpg','Card Holder Wallet',1);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (1,1,'Black','S',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (2,1,'Black','M',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (3,1,'Black','L',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (4,1,'Black','XL',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (5,1,'Black','XXL',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (6,1,'Off-white','S',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (7,1,'Off-white','M',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (8,1,'Off-white','L',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (9,1,'Off-white','XL',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (10,1,'Off-white','XXL',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (11,1,'Olive','S',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (12,1,'Olive','M',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (13,1,'Olive','L',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (14,1,'Olive','XL',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (15,1,'Olive','XXL',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (16,1,'Navy','S',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (17,1,'Navy','M',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (18,1,'Navy','L',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (19,1,'Navy','XL',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (20,1,'Navy','XXL',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (21,2,'Off-white','S',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (22,2,'Off-white','M',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (23,2,'Off-white','L',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (24,2,'Off-white','XL',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (25,2,'Off-white','XXL',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (26,3,'Olive','28',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (27,3,'Olive','30',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (28,3,'Olive','32',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (29,3,'Olive','34',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (30,3,'Olive','36',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (31,4,'Khaki','28',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (32,4,'Khaki','30',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (33,4,'Khaki','32',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (34,4,'Khaki','34',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (35,4,'Khaki','36',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (36,5,'Off-white','S',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (37,5,'Off-white','M',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (38,5,'Off-white','L',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (39,5,'Off-white','XL',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (40,5,'Off-white','XXL',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (41,6,'Maroon','S',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (42,6,'Maroon','M',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (43,6,'Maroon','L',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (44,6,'Maroon','XL',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (45,6,'Maroon','XXL',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (46,7,'Sage','S',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (47,7,'Sage','M',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (48,7,'Sage','L',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (49,7,'Sage','XL',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (50,7,'Sage','XXL',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (51,8,'Navy','S',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (52,8,'Navy','M',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (53,8,'Navy','L',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (54,8,'Navy','XL',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (55,8,'Navy','XXL',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (56,9,'White','39',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (57,9,'White','40',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (58,9,'White','41',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (59,9,'White','42',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (60,9,'White','43',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (61,9,'White','44',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (62,10,'Brown','39',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (63,10,'Brown','40',NULL,3);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (64,10,'Brown','41',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (65,10,'Brown','42',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (66,10,'Brown','43',NULL,12);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (67,10,'Brown','44',NULL,0);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (68,11,NULL,NULL,NULL,20);
INSERT INTO `variants` (`id`, `product_id`, `color`, `size`, `sku`, `stock`) VALUES (69,12,NULL,NULL,NULL,20);
